version: "3"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    container_name: elemental-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./nginx-vhost:/etc/nginx/vhost.d
      - "./nginx-conf:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elemental_net
networks:
  elemental_net:
    external: true
volumes:
  acme:
# volumes: # Names of volumes that out containers will share. Those will persist on docker's host machine.
#   nginx-conf:
#   nginx-vhost:
#   html:
#   certs:COPY
