version: "3" # Version of the Docker Compose file format
services:
  nginx-proxy:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./docker/html:/var/www/html
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./docker/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx-conf:/etc/nginx/conf.d
