version: "3"
services:
  mail-service:
    image: crccheck/hello-world
    environment:
      - VIRTUAL_HOST=${MAIL_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${MAIL_LETSENCRYPT_HOST}
      - VIRTUAL_PORT=${MAIL_VIRTUAL_PORT}
        #expose:
        #- "8000"
      #- LETSENCRYPT_TEST=true
  github-service:
    image: crccheck/hello-world
    environment:
      - VIRTUAL_HOST=${GITHUB_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${GITHUB_LETSENCRYPT_HOST}
      - VIRTUAL_PORT=${GITHUB_VIRTUAL_PORT}
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0.1-alpine
    container_name: elemental-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - DEFAULT_HOST=error.local
    networks:
      - elemental_net
networks:
  elemental_net:
    external: true
#volumes:
# acme:
#
# volumes: # Names of volumes that out containers will share. Those will persist on docker's host machine.
#   nginx-conf:
#   nginx-vhost:
#   html:
#   certs:COPY
