version: '3' # Version of the Docker Compose file format
services:
  mail-service:
    image: crccheck/hello-world
    environment:
      - VIRTUAL_HOST=${MAIL_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${MAIL_LETSENCRYPT_HOST}
      - VIRTUAL_PORT=${MAIL_VIRTUAL_PORT}
        #expose:
        #- "8000"
      #- LETSENCRYPT_TEST=true
  github-service:
    image: crccheck/hello-world
    environment:
      - VIRTUAL_HOST=${GITHUB_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${GITHUB_LETSENCRYPT_HOST}
      - VIRTUAL_PORT=${GITHUB_VIRTUAL_PORT}
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./nginx-conf:/etc/nginx/conf.d"
      - "./vhost:/etc/nginx/vhost.d"
      - "./html:/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:rw"
      - "./acme:/etc/acme.sh"
      - "./le_config:/app/letsencrypt_user_data:ro"
    depends_on: # Make sure we start nginx proxy container first
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${ACME_EMAIL}
    #  - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - elemental_net
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0.1-alpine
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
    #volumes:
    #  - ./vhost.d:/etc/nginx/vhost.d:ro
    # build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - DEFAULT_HOST=error.local
    networks:
      - elemental_net
networks:
  elemental_net:
    external: true
#volumes:
# acme:
#
# volumes: # Names of volumes that out containers will share. Those will persist on docker's host machine.
#   nginx-conf:
#   nginx-vhost:
#   html:
#   certs:COPY
